- .gitignore
- be15_DevEagles_BE/build.gradle
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/JacksonConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/WebSocketConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/GlobalExceptionHandler.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/exception/BusinessException.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/exception/ChatBusinessException.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/exception/ChatErrorCode.java
- be15_DevEagles_BE/src/main/resources/application-example.yml
- be15_DevEagles_BE/src/main/resources/logback-spring.xml
- close #13
- 채팅 기능 의존성 추가
- application-example.yml 추가
> feat:DEV-7 #comment 채팅 기능 의존성 설정,application-example.yml 추가함

- .github/workflows/scheduled-build-test.yml
> chore: git actions 빌드 테스트 수정

- .github/workflows/scheduled-build-test.yml
> chore:정기 빌드 테스트 워크플로우 경로 문제 수정

- .github/workflows/scheduled-build-test.yml
> chore:정기 빌드 테스트 wrapper 다운 불가 문제 수정

- .github/workflows/scheduled-build-test.yml
> chore: git actions 프론트 빌드 테스트 더미 컴포넌트 추가

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/entity/User.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/entity/UserStatus.java
- close #115 
- User 도메인 엔터티 생성
> Feature/dev 81 be User 도메인 entity 구현

- .github/workflows/scheduled-build-test.yml
> chore: git actions 프론트 빌드 yml 파서 에러 수정

- .github/workflows/scheduled-build-test.yml
> Chore/정기 빌드 테스트 워크플로우

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/MongoDBConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/dto/PagedResult.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/aggregate/ReadReceipt.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/repository/ChatMessageRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/repository/ChatRoomRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/repository/ChatroomParticipantRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/repository/ReadReceiptRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/repository/MongoChatMessageRepositoryImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/repository/MongoChatRoomRepositoryImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/repository/MongoChatroomParticipantRepositoryImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/repository/MongoReadReceiptRepositoryImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/repository/SpringDataMongoChatMessageRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/repository/SpringDataMongoChatRoomRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/repository/SpringDataMongoChatroomParticipantRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/repository/SpringDataMongoReadReceiptRepository.java
- close #23
- 몽고 DB Config 설정
- 채팅 관련 레포지토리 구현
- 몽고DB <=> 백엔드 어댑터 구현
> Feature/dev 16 be mongo db 연결 및 레포지토리 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/domain/aggregate/Todo.java
- close #79 
-  CQRS 모듈 구조 설계, todo 도메인 구현
> feat:DEV-52 #todolist CQRS 모듈 구조 설계, todo 도메인 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/aggregate/Team.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/aggregate/TeamMember.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/aggregate/TeamMemberId.java
- close #131
- Team 도메인 Entity 구현
[DEV-84]: https://beyond15th.atlassian.net/browse/DEV-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: DEV-84 #comment Team 도메인 Entity 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/BusinessException.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCodeType.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/GlobalExceptionHandler.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/exception/ChatBusinessException.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/exception/ChatErrorCode.java
- close 없음
- 글로벌 핸들러 세분화 및 로깅 추가(한글로 로그 볼 수 있게)
- common에 business exception 상위 추상화 클래스 구현 => 각 도메인의 비즈니즈 로직 처리 클래스에서 상속
- 도메인의 에러 코드의 형식을 강제하기 위한 ErrorCodeType 인터페이스 추가
- api 에러 반환에도 커스텀 예외 처리 메세지가 표시되도록 메서드 추가
> feature/예외처리 세분화

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/entity/User.java
- close #133 
- user_thumbnail_url 컬럼 추가
- not null 제약 조건 명시
> Fix/dev 84 be User entity 컬럼 수정 요청

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/dto/PagedResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/dto/Pagination.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/ChatMessageController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/ChatWebSocketController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/dto/request/ChatMessageRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/dto/response/ChatMessageResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/ChatMessageService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/ChatRoomService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/impl/ChatMessageServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/impl/ChatRoomServiceImpl.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/chat/command/service/ChatMessageServiceTest.java
- close #43
- 메세지 전송 서비스 구현
- 웹소켓 메세지 전송 컨트롤러 구현
- 페이지네이션 정보 api 반환에 담기 위한 dto 객체 생성
> Feature/dev 26 be 메세지 저장 조회 삭제 서비스 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/domain/aggregate/Comment.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/domain/aggregate/Worklog.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/infrastructure/repository/JpaWorklogRepository.java
-  @builder 클래스 위에 붙이는 방식에서 생성자 위에 붙이는 방식으로 수정
> Refactor/dev 82 be worklog comment 도메인 entity 구현 및 cqrs 패턴 설정

- be15_DevEagles_BE/build.gradle
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/RestTemplateConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/AiChatController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/ChatWebSocketController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/AiChatService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/MoodInquiryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/PromptTemplate.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/impl/AiChatServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/impl/MoodInquiryServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/aggregate/UserMoodHistory.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/exception/GeminiApiException.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/exception/HuggingFaceApiException.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/repository/ChatMessageRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/repository/UserMoodHistoryRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/adapters/GeminiApiAdapter.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/adapters/HuggingFaceApiAdapter.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/repository/MongoChatMessageRepositoryImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/repository/SpringDataMongoChatMessageRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/config/mongodb/MongoDBConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/config/websocket/WebSocketConnectionEventHandler.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/impl/AiChatServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/impl/MoodInquiryServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/adapters/GeminiApiAdapterIntegrationTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/adapters/GeminiApiAdapterTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/adapters/HuggingFaceApiAdapterIntegrationTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/adapters/HuggingFaceApiAdapterTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/chat/command/infrastructure/repository/MongoChatMessageRepositoryIntegrationTest.java
- be15_DevEagles_BE/src/test/resources/application.properties
- close #49
- Gemini API 질문 생성 기능, JSON 파싱 및 에러 처리, 경계 처리 DTO 생성, 바운더리 어댑터 구현
- 허깅페이스 감정 분석 모델 API 호출, JSON 파싱 및 에러 처리 경계 처리 DTO 생성, 바운더리 어댑터 구현
- 어댑터 단위 테스트
- Gemini API 통합 테스트
- 허깅페이스 API 통합 테스트
- 몽고DB 통합 테스트
> Feature/dev 29 be gemini api 연결 및 채팅 감정 분석 기능 구현

- be15_DevEagles_BE/src/main/resources/application-example.yml
- close 없음
- application-example.yml 업데이트
-
> Chore/application example.yml

- be15_DevEagles_BE/build.gradle
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/controller/UserCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/dto/request/UserCreateRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/UserCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/UserCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/domain/aggregate/User.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/domain/aggregate/UserStatus.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/domain/exception/UserBusinessException.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/domain/exception/UserErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/entity/UserStatus.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/repository/UserRepository.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/impl/UserCommandServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/user/command/exception/UserExceptionTest.java
- close #67 
- build.gradle validation 의존성 추가
- User 엔터티 패키지 경로 변경
- 회원 가입 기능 구현
- 비밀번호 암호화
> Feature/ dev 47 be 회원 가입 기능 구현

- .gitignore
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/aggregate/TeamMember.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/dto/request/CreateTodoRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/dto/response/TodoResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/service/TodoService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/domain/aggregate/Todo.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/domain/repository/TodoRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/exception/InvalidTodoDateException.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/exception/TodoErrorCode.java
- be15_DevEagles_BE/src/main/resources/application.yml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/service/TodoServiceTest.java
- close #81 
- yml 설정
- todo 작성 서비스 구현 및 test 코드 작성
- 에러코드 작성
> Feature/dev 54 be todo 작성 서비스 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/service/TodoService.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/service/TodoServiceTest.java
- close #168 
- todo 한 번에 여러 개 작성할 수 있게 수정
> Fix/dev 109 be todo 작성 service fix

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/service/TodoService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/exception/TodoErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/exception/TodoNotFoundException.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/service/TodoServiceTest.java
- close #86 
- todo 완료 처리 서비스 구현
- test 코드 작성
> feature:DEV-59 #comment todolist 완료 서비스 구현, 테스트 코드 작성

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/controller/TeamController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/dto/request/CreateTeamRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/dto/response/CreateTeamResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/TeamCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/impl/TeamCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/exception/TeamBusinessException.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/exception/TeamErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/repository/TeamRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/infrastructure/repository/JpaTeamRepository.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/TeamCommandServiceTest.java
- close #85 
- 팀 생성 기능 구현 
- JWT 구현 완료 시 controller 로직 수정 예정
> feat: DEV-58 #comment 팀 생성 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/service/TodoService.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/service/TodoServiceTest.java
- close #84 
- todo 삭제 서비스 구현
- test 코드 작성
> Feature/dev 57 be todo 삭제 서비스 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/controller/TodoController.java
- close #82 
- todo command 컨트롤러 구현
- postman 테스트 성공
> Feature/dev 55 be todo command 컨트롤러 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/HMACKeyGenerator.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/RedisConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/JwtAuthenticationFilter.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/JwtTokenProvider.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/RestAccessDeniedHandler.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/RestAuthenticationEntryPoint.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/dto/response/TokenResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/model/CustomUser.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/CustomUserDetailsService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/RefreshTokenService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/RefreshTokenServiceImpl.java
- close #68 
- spring security 적용을 위한 애플리케이션 환경 파일 적용
- jwt token 발급을 위한 코드
> Feature/dev 48 be spring security 적용을 위한 환경 변수 및 애플리케이션 구성 파일 설정

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/controller/AuthController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/dto/request/LoginRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/repository/UserRepository.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/impl/AuthServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/auth/command/exception/AuthExceptionTest.java
- close #143 
- 사용자 로그인 서비스 기능 구현
- 한 달 이내에 탈퇴한 휴면 계정 로그인
- 로그인 실패 시 예외 처리
> Feature/ dev 89 be #comment 로그인 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/controller/AuthController.java
> Refactor/ dev 89 be 로그인 시 refreshToken 쿠키 저장

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/controller/AuthController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthServiceImpl.java
- close #183 
- 로그아웃 시 refreshToken 검증
- 검증 완료 시 refreshToken 및 쿠키 세션 만료
> Feature/ dev 113 be 회원 로그아웃 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/controller/TeamController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/dto/request/InviteTeamMemberRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/TeamCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/impl/TeamCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/exception/TeamErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/repository/TeamMemberRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/repository/TeamRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/infrastructure/repository/JpaTeamMemberRepository.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/CreateTeamTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/InviteTeamMemberTest.java
- close #92 
- 팀원 초대 기능 구현
- 팀 생성 시 팀장도 TeamMember로 저장되도록 로직 추가
- Service Test Code 분리
> feat: DEV-65 #comment 팀원 초대 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/controller/TodoController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/service/TodoService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/domain/aggregate/Todo.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/exception/TodoErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/exception/TodoUnauthorizedAccessException.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/service/TodoServiceTest.java
- close #179 
- test 코드 추가
- todo부분 로그인 정보 확인
- security config 추가
> fix:DEV-112 #comment todo command 전체 수정

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/controller/TeamController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/dto/request/FireTeamMemberRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/TeamCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/impl/TeamCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/aggregate/TeamMember.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/exception/TeamErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/repository/TeamMemberRepository.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/FireTeamMemberTest.java
> feat: DEV-67 #comment 팀원 추방 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/controller/UserCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/dto/request/UserUpdateRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/UserCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/UserCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/domain/aggregate/User.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/impl/UserCommandServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/user/command/exception/UserExceptionTest.java
- close #144 
- 회원 정보 수정 전 회원 비밀번호 유효성 검증
- 회원 정보 수정 (이름, 전화번호) 변경 기능 구현
> Feature/dev 90 be 회원 정보 변경 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/dto/response/TodoDetailResponse.java
- be15_DevEagles_BE/src/main/resources/mappers/features/todolist/TodoQueryMapper.xml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/service/TodoQueryServiceTest.java
- close #233 
- 상세조회 시 팀이름 보이게 수정
-
> fix:DEV-153 #comment todo 상세 조회 서비스 수정

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/dto/response/MyCalendarTodoResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/mapper/TodoCalendarQueryMapper.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/service/TodoCalendarQueryService.java
- be15_DevEagles_BE/src/main/resources/mappers/features/todolist/TodoCalendarQueryMapper.xml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/service/TodoCalendarQueryServiceTest.java
- close #108 
- 내 캘린더 조회 서비스 구현 (메인페이지)
> feature:DEV-73 #comment 내 캘린더 조회 서비스 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/dto/response/MyDdayTodoPage.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/dto/response/MyDdayTodoResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/mapper/TodoDdayQueryMapper.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/service/TodoDdayQueryService.java
- be15_DevEagles_BE/src/main/resources/mappers/features/todolist/TodoDdayQueryMapper.xml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/service/TodoDdayQueryServiceTest.java
- close #109 
-  내 todo 리스트 조회 서비스 구현
- 페이징 처리
- 테스트 코드 작성
> feature:DEV-74 #comment 내 todo 리스트 조회 서비스 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/JwtAuthenticationFilter.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/JwtTokenProvider.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/controller/AuthController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthServiceImpl.java
- 
- 로그아웃 시 accessToken redis 블랙리스트 추가
> Refactor/ DEV-113-BE 로그아웃 시 accessToken 만료 추가

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/controller/TeamController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/TeamCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/impl/TeamCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/aggregate/Team.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/exception/TeamErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/repository/TeamMemberRepository.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/DeleteTeamTest.java
> feat: DEV-64 #comment 팀 삭제 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/controller/UserCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/dto/request/UserPasswordRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/UserCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/UserCommandServiceImpl.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/impl/UserCommandServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/user/command/exception/UserExceptionTest.java
- close #145 
- 회원 비밀번호 변경 기능 구현
- user domain 테스트 코드 변경
> feature/ dev 91 be 회원 비밀번호 변경 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/query/controller/TeamQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/query/dto/response/MyTeamListResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/query/mapper/TeamMapper.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/query/service/TeamQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/query/service/impl/TeamQueryServiceImpl.java
- be15_DevEagles_BE/src/main/resources/mappers/features/team/TeamMapperQuery.xml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/query/application/service/MyTeamListTest.java
> feat: DEV-60 #comment 팀 목록 조회 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/controller/AuthController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/dto/request/UserFindIdRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/dto/response/UserFindIdResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/repository/UserRepository.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/impl/AuthServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/auth/command/exception/AuthExceptionTest.java
- close #146 
- 회원 아이디 찾기 기능 구현
- Auth 관련 테스트 코드 수정
> Feature/ DEV-92-BE #comment 회원 아이디 찾기 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/controller/UserCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/UserCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/UserCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/domain/aggregate/User.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/impl/UserCommandServiceTest.java
> Feature/DEV-154-BE #comment 회원 탈퇴 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/query/controller/TeamQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/query/dto/response/TeamMemberResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/query/mapper/TeamMapper.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/query/service/TeamQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/query/service/impl/TeamQueryServiceImpl.java
- be15_DevEagles_BE/src/main/resources/mappers/features/team/TeamMapperQuery.xml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/query/application/service/MyTeamListTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/query/application/service/TeamMemberListTest.java
> feat: DEV-61 #comment 팀원 조회 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/controller/AuthController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/model/CustomUser.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/CustomUserDetailsService.java
- close #193 
- 로그인 시 사용자의 인증 상태 확인을 위한 로직 추가
> Feature/ dev 117 be #comment spring-security-role-저장

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/dto/response/MyTeamDdayTodoPage.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/dto/response/MyTeamDdayTodoResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/mapper/TodoDdayQueryMapper.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/service/TodoDdayQueryService.java
- be15_DevEagles_BE/src/main/resources/mappers/features/todolist/TodoDdayQueryMapper.xml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/service/TodoDdayQueryServiceTest.java
- close #114 
- 팀에 대한 내 todo 리스트 조회 서비스 구현
- 테스트 코드 작성
> feature:DEV-80 #comment 팀에 대한 내 todo 리스트 조회 서비스 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/dto/response/TeamFilteredTodoResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/mapper/TodoTeamQueryMapper.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/service/TodoTeamQueryService.java
- be15_DevEagles_BE/src/main/resources/mappers/features/todolist/TodoTeamQueryMapper.xml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/service/TodoTeamQueryServiceTest.java
- close #232 
- 팀 todo 리스트 목록 조회 서비스 구현 (유저 필터링 가능)
- 테스트 코드 작성
- pagination 공통 컴포넌트 사용
> feature:DEV-152 #comment 팀 todo 리스트 목록 조회 서비스 구현 (유저 필터링 가능)

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/dto/response/TeamResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/controller/WorklogCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/dto/request/SearchWorklogRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/dto/response/WorklogResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/service/PageRequestUtil.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/service/WorklogService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/service/impl/WorklogServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/domain/repository/WorklogRepository.java
- close #162 
- 내 업무일지 내역 조회하기
> feature:DEV-106 나의 업무일지 조회하기

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/timecapsule/controller/TimecapsuleController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/timecapsule/dto/TimecapsuleCreateRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/timecapsule/entity/Timecapsule.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/timecapsule/exception/TimecapsuleNotFoundException.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/timecapsule/repository/TimecapsuleRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/timecapsule/service/TimecapsuleService.java
> [BE] 타입캡슐 생성

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
> Refactor/ DEV-158-BE #comment 스프링 시큐리티 필터 체인 수정

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/controller/TeamController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/TeamCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/impl/TeamCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/domain/aggregate/Team.java
- be15_DevEagles_BE/src/main/resources/application.yml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/CreateTeamTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/DeleteTeamTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/FireTeamMemberTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/InviteTeamMemberTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/TransferLeaderTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/UploadTeamThumbnailTest.java
- close #98 
- S3 업로드 및 DB URL 저장
- Test Code refactor
> Feature/dev 71 be 팀 썸네일 변경 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/impl/TeamCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/controller/WorklogCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/dto/response/WorklogDetailResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/service/WorklogService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/service/impl/WorklogServiceImpl.java
> Feature/dev 87 be 업무일지 상세조회 기능 구현하기

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/controller/AuthController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/dto/request/UserFindPwdRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/MailService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/repository/UserRepository.java
- be15_DevEagles_BE/src/main/resources/application.yml
- close #147 
- 비밀번호 찾기를 위한 이메일 전송
- 이메일 인증 후 인증코드 검증
> Feature/dev 93 be 회원 비밀번호 찾기 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/aggregate/UserMoodHistory.java
- be15_DevEagles_FE/eslint.config.js
- be15_DevEagles_FE/src/api/axios.js
- be15_DevEagles_FE/src/components/common/layout/Layout.vue
- be15_DevEagles_FE/src/components/common/layout/index.js
- be15_DevEagles_FE/src/features/chat/api/api.js
- be15_DevEagles_FE/src/features/chat/api/chatService.js
- be15_DevEagles_FE/src/features/chat/api/webSocketService.js
- be15_DevEagles_FE/src/features/chat/components/ChatRoomListView copy.vue
- be15_DevEagles_FE/src/features/chat/components/ChatRoomListView.vue
- be15_DevEagles_FE/src/features/chat/components/ChatWindow.vue
- be15_DevEagles_FE/src/features/chat/config/chatConfig.js
- be15_DevEagles_FE/src/main.js
- be15_DevEagles_FE/src/store/auth.js
- package.json
- close #152
- 전역 웹소켓, 스톰프, SockJS 설정
- 일부 모킹 데이터 제거 후 백엔드 연결 테스트
-
> Feature/dev 97 fe 웹소켓 설정 및 연결

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/controller/CommentCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/dto/request/CommentCreateRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/dto/response/CommentResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/service/CommentService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/service/impl/CommentServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/domain/aggregate/Comment.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/domain/exception/CommentBusinessException.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/domain/exception/CommentErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/domain/repository/CommentRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/service/impl/WorklogServiceImpl.java
> feature:DEV-102 댓글 등록하기

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/controller/CommentCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/service/CommentService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/service/impl/CommentServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/domain/repository/CommentRepository.java
> feature:DEV-104 댓글 조회하기

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/controller/CommentCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/dto/request/CommentUpdateRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/service/CommentService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/service/impl/CommentServiceImpl.java
> feature:DEV-103 댓글 수정하기

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/controller/UserCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/UserCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/UserCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/domain/aggregate/User.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/domain/exception/UserErrorCode.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/impl/UserCommandServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/user/command/exception/UserExceptionTest.java
- close #276 
- 회원 가입 시 프로필 이미지 S3 저장
- 프로필 이미지 변경 시 S3 저장
> Feature/DEV 159 BE #comment 회원 프로필 이미지 저장

- .github/workflows/scheduled-build-test.yml
- be15_DevEagles_FE/public/assets/css/components.css
- be15_DevEagles_FE/src/assets/css/index.css
- be15_DevEagles_FE/src/components/common/components/BaseButton.vue
- be15_DevEagles_FE/src/components/common/components/BaseForm.vue
- be15_DevEagles_FE/src/components/common/components/BaseModal.vue
- be15_DevEagles_FE/src/components/common/components/Pagaination.vue
- be15_DevEagles_FE/src/plugin/axios.js
- be15_DevEagles_FE/src/views/Home.vue
- be15_DevEagles_FE/src/views/Reference.vue
- close #293
- 기본 버튼
- 기본 폼(라디오버튼, 체크박스, 인풋, 텍스트 에리어 등)
- 기본 모달
- 페이지네이션
- 예제 생성
> Feature/dev 169 fe 공통 컴포넌트 생성 예제 생성 스타일 정의

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/controller/CommentCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/service/CommentService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/service/impl/CommentServiceImpl.java
> feature:DEV-105 댓글 삭제하기

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/dto/request/FindInfoRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/service/impl/WorklogServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/domain/aggregate/SearchType.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/domain/repository/WorklogRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/query/controller/SearchInfoController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/query/mapper/WorklogMapper.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/query/service/WorklogSearchQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/query/service/impl/WorklogSearchQueryServiceImpl.java
- be15_DevEagles_BE/src/main/resources/mappers/features/worklog/WorklogMapper.xml
> Feature/dev 171 be 검색 기능 

- be15_DevEagles_FE/src/components/common/layout/TeamSidebar.vue
- be15_DevEagles_FE/src/features/team/api/team.js
- be15_DevEagles_FE/src/features/team/components/CreateTeamModal.vue
- be15_DevEagles_FE/src/features/team/components/TeamMemberList.vue
- be15_DevEagles_FE/src/features/team/router.js
- be15_DevEagles_FE/src/store/team.js
- close #213 
-팀 생성 모달 구현 및 api 연동
-팀 목록 api 연동
-팀원 목록 api 연동
> feat: DEV-137-FE #comment 팀 생성 컴포넌트 모달 구현 및 api 연동

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/timecapsule/command/application/controller/TimecapsuleController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/timecapsule/command/application/service/TimecapsuleService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/timecapsule/command/repository/TimecapsuleRepository.java
- #289 
-  사용자가 설정한 날짜에 타임캡슐이 출력되는 기능을 구현
-  설정한 날짜가 지나도 active 상태인 타임캡슐이 출력이 가능하도록 기능 구현
> Feature/dev 168 be 타입캡슐 출력

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/controller/TodoQueryController.java
- be15_DevEagles_BE/src/main/resources/mappers/features/todolist/TodoQueryMapper.xml
> fix:DEV-173 #comment BE todo 상세 조회 컨트롤러 구현

- be15_DevEagles_FE/src/router/index.js
> fix : ErrorPage import 중복 삭제

- be15_DevEagles_FE/src/components/common/layout/Header.vue
- be15_DevEagles_FE/src/features/user/api/user.js
> Feature/ DEV-175-fe-로그아웃-api-연동

- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/impl/UserCommandServiceTest.java
- close #305 
- UserCommandServiceTest : s3 NullPointerException 해결
> Fix/ DEV-172-BE #comment 회원가입 정보 수정 단위 테스트 수정 요청

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/dto/response/NotificationSettingResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/dto/response/NotificationToggleResponse.java
- be15_DevEagles_FE/package.json
- be15_DevEagles_FE/src/assets/css/toast.css
- be15_DevEagles_FE/src/composables/useNotifications.js
- be15_DevEagles_FE/src/features/chat/api/chatService.js
- be15_DevEagles_FE/src/main.js
- close #156
- 토스티피케이션 설정
- 알림 기능 구현
- 백엔드 알림 설정 동기화 서비스 추가
> Feature/dev 100 be 채팅 알림 기능 구현

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/query/dto/response/TeamInformationResponse.java
- be15_DevEagles_BE/src/main/resources/mappers/features/team/TeamMapperQuery.xml
- be15_DevEagles_FE/package.json
- be15_DevEagles_FE/src/components/common/layout/Sidebar.vue
- be15_DevEagles_FE/src/features/team/components/TeamInformationForm.vue
- be15_DevEagles_FE/src/features/team/components/TeamMemberInviteModal.vue
- be15_DevEagles_FE/src/features/team/components/UpdateTeamThumbnailModal.vue
- be15_DevEagles_FE/src/features/team/router.js
- be15_DevEagles_FE/src/features/team/views/TeamInformationView.vue
- be15_DevEagles_FE/src/router/index.js
- be15_DevEagles_FE/tsconfig.json
- close #211 
-팀 썸네일 변경 모달 생성
-팀원 초대 모달 생성
-팀 정보 페이지 구현
-teaminfo 응답 필드 추가
> Feature/dev 135 fe 팀 정보 페이지 구현

- be15_DevEagles_FE/src/features/todolist/api/api.js
- be15_DevEagles_FE/src/features/todolist/views/MyCalendarView.vue
- be15_DevEagles_FE/src/features/todolist/views/TeamCalendarView.vue
- close #215 
- todolist 조회 구현
- 업무일지 작성 여부 구현
> feat:DEV-139 FE #comment 팀 todolist, 개인 todolist 구현

- be15_DevEagles_FE/src/features/team/api/team.js
- be15_DevEagles_FE/src/features/team/components/TeamInformationForm.vue
- be15_DevEagles_FE/src/features/team/components/TeamMemberInviteModal.vue
- [] BE
- close #221 
-팀원 초대 api 연동
> feat: DEV-145-FE #comment 팀원 초대 API 연동

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/dto/response/ChatMessageResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/PromptTemplate.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/impl/AiChatServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/impl/ChatMessageServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/aggregate/UserMoodHistory.java
- be15_DevEagles_FE/src/features/chat/api/aiChatService.js
- be15_DevEagles_FE/src/features/chat/api/chatService.js
- be15_DevEagles_FE/src/features/chat/api/webSocketService.js
- be15_DevEagles_FE/src/features/chat/components/AiMessageBubble.vue
- be15_DevEagles_FE/src/features/chat/components/ChatWindow.vue
- be15_DevEagles_FE/src/features/chat/composables/useAiChat.js
- be15_DevEagles_FE/src/features/chat/composables/useChatWebSocket.js
- be15_DevEagles_FE/src/features/chat/utils/aiMessageUtils.js
- be15_DevEagles_FE/src/features/chat/utils/chatUtils.js
> Feature/dev 177 fe ai 답변 기능

- be15_DevEagles_FE/src/features/team/api/team.js
- be15_DevEagles_FE/src/features/team/components/TeamInformationForm.vue
> feat: DEV-145-FE #comment 팀원 추방 API 연동

- be15_DevEagles_FE/src/features/team/api/team.js
- be15_DevEagles_FE/src/features/team/components/TeamInformationForm.vue
- close #224 
-팀장 권한 양도 api 연동
> feat: DEV-145-FE #comment 팀장 권한 양도 API 연동

- be15_DevEagles_FE/src/features/team/api/team.js
- be15_DevEagles_FE/src/features/team/components/TeamInformationForm.vue
> feat: DEV-144-FE #comment 팀 탈퇴 기능 API 연동

- be15_DevEagles_FE/src/components/common/layout/Layout.vue
- be15_DevEagles_FE/src/features/user/api/user.js
- be15_DevEagles_FE/src/features/user/components/PasswordCheckModal.vue
- be15_DevEagles_FE/src/features/user/components/ProfileUpload.vue
- be15_DevEagles_FE/src/features/user/components/UserProfileCard.vue
- be15_DevEagles_FE/src/features/user/mypageRouter.js
- be15_DevEagles_FE/src/features/user/views/MyPageView.vue
- be15_DevEagles_FE/src/features/user/views/UserEditPageView.vue
- close #210 
- 수정 페이지 및 수정 api 연동
- 비밀번호 검증 페이지 및 api 연동
> Feature/dev 134 fe 회원정보 수정 화면 생성 및 api 연동

- be15_DevEagles_FE/src/features/user/api/user.js
- be15_DevEagles_FE/src/features/user/mypageRouter.js
- be15_DevEagles_FE/src/features/user/views/MyPageView.vue
- be15_DevEagles_FE/src/features/user/views/PwdEditPageView.vue
- be15_DevEagles_FE/src/features/user/views/UserEditPageView.vue
- close #212
- 비밀번호 변경 화면 및 api 연동
- 회원정보 / 비밀번호 변경 후 확인 모달 생성
> Feature/ DEV-136-fe-비밀번호-변경-화면-생성-및-api-연동

- be15_DevEagles_FE/src/features/user/views/LoginView.vue
> refactor : 로그인 이벤트 엔터키로 호출

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/dto/request/FindInfoRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/service/PageRequestUtil.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/query/mapper/WorklogMapper.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/query/service/impl/WorklogSearchQueryServiceImpl.java
- be15_DevEagles_BE/src/main/resources/mappers/features/worklog/WorklogMapper.xml
- be15_DevEagles_FE/src/features/comment/api/comment.js
- be15_DevEagles_FE/src/features/comment/components/CommentForm.vue
- be15_DevEagles_FE/src/features/comment/view/CommentList.vue
- be15_DevEagles_FE/src/features/worklog/router.js
- be15_DevEagles_FE/src/features/worklog/views/WorklogDetailView.vue
> feat:DEV-186-fe-댓글-등록

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/dto/request/CommentCreateRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/service/impl/CommentServiceImpl.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/comment/command/application/service/impl/CommentServiceImplTest.java
> chore:comment test code 작성

- be15_DevEagles_FE/src/assets/css/toast.css
- be15_DevEagles_FE/src/components/common/layout/RightSidebar.vue
- be15_DevEagles_FE/src/components/common/layout/TeamSidebar.vue
- be15_DevEagles_FE/src/features/chat/api/chatService.js
- be15_DevEagles_FE/src/features/chat/components/ChatList.vue
- be15_DevEagles_FE/src/features/chat/components/ChatNotificationToast.vue
- be15_DevEagles_FE/src/features/chat/components/ChatWindow.vue
- be15_DevEagles_FE/src/features/chat/composables/useChatWindow.js
- be15_DevEagles_FE/src/features/chat/composables/useNotifications.js
- be15_DevEagles_FE/src/features/chat/utils/chatUtils.js
- be15_DevEagles_FE/src/features/team/components/TeamMemberList.vue
- be15_DevEagles_FE/src/store/chat.js
- close #365
- 썸네일 백엔드 연동
- 알림 디자인 수정
- 알림 구독 기능 이상 해결
- 채팅 컴포넌트 디자인 수정
> feat: DEV-189 채팅 팀 목록 백엔드 썸네일 적용, 알림 디자인 수정, 일부 디자인 수정

- be15_DevEagles_FE/src/components/common/layout/Sidebar.vue
- be15_DevEagles_FE/src/features/timecapsule/api/timecapsuleApi.js
- be15_DevEagles_FE/src/features/timecapsule/components/TimecapsuleCreateForm.vue
- be15_DevEagles_FE/src/features/timecapsule/composables/useTimecapsule.js
- be15_DevEagles_FE/src/features/timecapsule/router.js
- be15_DevEagles_FE/src/features/timecapsule/views/TimecapsuleCreatePage.vue
- be15_DevEagles_FE/src/router/index.js
- #376 
- 타임캡슐 생성 화면 페이지 구현
- 사이드바에 타임캡슐 관련 토글 추가
> feat:DEV-194 fe 타임캡슐 생성

- be15_DevEagles_BE/build.gradle
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/ChatWebSocketController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/UserStatusController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/impl/ChatRoomServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/config/websocket/WebSocketAuthInterceptor.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/config/websocket/WebSocketConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/config/websocket/WebSocketEventHandler.java
- be15_DevEagles_FE/src/App.vue
- be15_DevEagles_FE/src/components/common/layout/Header.vue
- be15_DevEagles_FE/src/components/common/layout/RightSidebar.vue
- be15_DevEagles_FE/src/features/chat/api/chatService.js
- be15_DevEagles_FE/src/features/chat/api/userStatusService.js
- be15_DevEagles_FE/src/features/chat/api/webSocketService.js
- be15_DevEagles_FE/src/features/chat/components/ChatList.vue
- be15_DevEagles_FE/src/features/chat/components/ChatNotificationToast.vue
- be15_DevEagles_FE/src/features/chat/components/ChatWindow.vue
- be15_DevEagles_FE/src/features/chat/composables/useChatRoom.js
- be15_DevEagles_FE/src/features/chat/composables/useChatWindow.js
- be15_DevEagles_FE/src/features/chat/utils/chatUtils.js
- be15_DevEagles_FE/src/features/team/components/TeamMemberList.vue
- be15_DevEagles_FE/src/features/user/views/LoginView.vue
- be15_DevEagles_FE/src/store/auth.js
- be15_DevEagles_FE/src/store/chat.js
- be15_DevEagles_FE/src/store/team.js
- be15_DevEagles_FE/src/store/userStatus.js
- close #368
- 사용자의 상태(온라인, 오프라인 표시)
- 웹소켓 JWT 인터셉터 설정
- 팀 목록 선택시 타팀 채팅방 조회되던 문제 수정
> Feature/dev 190 fe 사용자 상태 온라인 오프라인 관리 기능 구현

- be15_DevEagles_FE/src/features/comment/api/comment.js
- be15_DevEagles_FE/src/features/comment/components/CommentForm.vue
- be15_DevEagles_FE/src/features/comment/view/CommentList.vue
- be15_DevEagles_FE/src/features/worklog/views/WorkCreate.vue
- be15_DevEagles_FE/src/features/worklog/views/WorkLogListView.vue
- be15_DevEagles_FE/src/features/worklog/views/WorklogDetailView.vue
> fix:DEV-192-fe-댓글-삭제

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/ChatWebSocketController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/UserStatusController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/config/websocket/WebSocketEventHandler.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/infrastructure/adapters/ChatRedisSyncScheduler.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/query/infrastructure/repository/MongoMessageQueryRepositoryImpl.java
- be15_DevEagles_FE/src/App.vue
- be15_DevEagles_FE/src/components/common/layout/Header.vue
- be15_DevEagles_FE/src/components/common/layout/Layout.vue
- be15_DevEagles_FE/src/components/common/layout/RightSidebar.vue
- be15_DevEagles_FE/src/features/chat/api/userStatusService.js
- be15_DevEagles_FE/src/features/chat/api/webSocketService.js
- be15_DevEagles_FE/src/features/chat/components/ChatList.vue
- be15_DevEagles_FE/src/features/chat/components/ChatWindow.vue
- be15_DevEagles_FE/src/features/chat/components/MessageReadStatus.vue
- be15_DevEagles_FE/src/features/chat/composables/useDebounce.js
- be15_DevEagles_FE/src/features/team/components/TeamMemberList.vue
- be15_DevEagles_FE/src/features/user/views/LoginView.vue
- be15_DevEagles_FE/src/main.js
- be15_DevEagles_FE/src/store/auth.js
- be15_DevEagles_FE/src/store/chat.js
- be15_DevEagles_FE/src/store/userStatus.js
- close 없음
- 웹소켓 중복 연결 방지, 로그아웃시 세션 명시적 해제 등 세션 관련 코드 전부 수정
- 웹소켓 연결 실패 폴백 처리 강화
- 사용자 로그인, 로그아웃시 온라인, 오프라인 상태 바로 반영되도록 수정
> fix: DEV-190 웹소켓 연결 관련 문제 해결 (여러 컴포넌트에서 초기화 하는 문제 등)

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/JwtTokenProvider.java
> fix : DEV-197-be-refresh-token-재발급

- be15_DevEagles_FE/src/App.vue
- be15_DevEagles_FE/src/features/timecapsule/api/timecapsuleApi.js
- be15_DevEagles_FE/src/features/timecapsule/components/TimecapsuleCreateForm.vue
- #289 
- 타임캡슐 출력 기능 구현, 모달 생성
- 타임캡슐 생성 폼에 팀 이름 추가
> feat:DEV-164 fe 타임캡슐 출력

- be15_DevEagles_BE/gradle/wrapper/gradle-wrapper.properties
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/config/websocket/WebSocketEventHandler.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/infrastructure/adapters/ChatRedisSyncScheduler.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/query/infrastructure/repository/MongoMessageQueryRepositoryImpl.java
- be15_DevEagles_FE/src/components/common/layout/Header.vue
- be15_DevEagles_FE/src/components/common/layout/Layout.vue
- be15_DevEagles_FE/src/components/common/layout/RightSidebar.vue
- be15_DevEagles_FE/src/features/chat/api/userStatusService.js
- be15_DevEagles_FE/src/features/chat/components/ChatList.vue
- be15_DevEagles_FE/src/features/chat/composables/useDebounce.js
- be15_DevEagles_FE/src/store/auth.js
- be15_DevEagles_FE/src/store/chat.js
- be15_DevEagles_FE/src/store/userStatus.js
- be15_DevEagles_FE/src/utils/logger.js
> Fix/rollback to read status UI

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/AiChatController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/UserStatusController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/impl/TeamCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/impl/TeamMemberCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/UserCommandServiceImpl.java
- be15_DevEagles_FE/src/components/common/layout/RightSidebar.vue
- be15_DevEagles_FE/src/features/chat/components/ChatList.vue
- be15_DevEagles_FE/src/features/chat/utils/chatUtils.js
- be15_DevEagles_FE/src/store/chat.js
- be15_DevEagles_FE/src/store/team.js
- close #395
- 팀 생성시 전체 채팅방 생성, 회원가입시 AI 채팅방 생성
- 팀 초대시 팀 채팅방 자동 추가, 팀 추방시 채팅방에서 삭제
- 프론트엔드 자잘한 UI 수정(전체 채팅방)
> Feature/dev 198 be 채팅방 생성 비즈니스 로직 적용 및 swagger

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/command/application/controller/TodoController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/todolist/query/application/controller/TodoQueryController.java
> Chore/dev 201 be swagger 작성

- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/CreateTeamTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/DeleteTeamTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/FireTeamMemberTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/InviteTeamMemberTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/TransferLeaderTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/UploadTeamThumbnailTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/team/command/application/service/WithdrawTeamTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/user/command/application/service/impl/UserCommandServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/user/command/exception/UserExceptionTest.java
- close #405 
- 팀 유저 관련 채팅룸 추가로 인한 테스트코드 수정
> Fix/dev 202 be 팀 유저 테스트코드 수정

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/controller/CommentCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/controller/SummaryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/command/application/controller/WorklogCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/worklog/query/controller/SearchInfoController.java
> chore: swagger 작성

- be15_DevEagles_FE/src/features/todolist/components/TodoCalendar.vue
- close #407 
- 풀캘린더 날짜 부분 한글로 수정
> Fix/dev 203 fe 풀캘린더 날짜 부분 한글로 수정

- be15_DevEagles_FE/src/features/worklog/components/WorkLog.vue
- be15_DevEagles_FE/src/features/worklog/views/WorkLogListView.vue
> fix: 업무 목록 페이지 수정

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/dto/response/CommentResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/application/service/impl/CommentServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/comment/command/domain/aggregate/Comment.java
> fix: 댓글 기능 수정 - 시간 수정

- be15_DevEagles_FE/src/components/common/layout/Header.vue
> feat: DEV-199 헤더 오류 수정 (user 참조 삭제)

- be15_DevEagles_BE/Dockerfile
> refactor: DEV-209 #comment CI/CD 환경 구축 및 테스트

- docker-compose.yml
> chore: DEV-209 #comment CI/CD 환경 구축 및 테스트-docker

- be15_DevEagles_FE/src/App.vue
- #435 
- 타임캡슐 출력 화면의 UI를 수정함
-
> feat:DEV-211 fe 타임캡슐 출력 화면 UI 수정

- be15_DevEagles_FE/src/components/common/layout/RightSidebar.vue
- be15_DevEagles_FE/src/features/team/components/TeamMemberList.vue
- be15_DevEagles_FE/src/features/timecapsule/views/TimecapsuleList.vue
- be15_DevEagles_FE/src/features/worklog/views/WorkCreate.vue
- close 이미 닫힘
- alert 호출 모두 토스티피케이션으로 대체
-
> feat: DEV-212 alert창 토스티피케이션으로 모두 대체

- .github/workflows/scheduled-build-test.yml
> chore: buildtest update

- .gitignore
> feat : gitignore 설정 변경

- README.md
> README_v3.md

- be15_DevEagles_FE/Dockerfile
> refactor: DEV-204-FE #comment 버튼 디자인 수정
